services:
  mysql:
    image: mysql:8.2
    container_name: dockerized_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
    networks:
      - localnet

  backend:
    depends_on:
      - mysql
    container_name: dockerized_backend
    restart: always
    build:
      context: ./back-end/back-end-kamban-app
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql:3306
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE
    ports:
      - '8080:8080'
    networks:
      - localnet

  frontend:
    depends_on:
      - backend
    container_name: dockerized_frontend
    restart: always
    build:
      context: ./front-end/front-end-kanban-app
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_HOST
    ports:
      - '80:80'
    networks:
      - localnet

volumes:
  mysql-data:

networks:
  localnet:
    driver: bridge
