version: '3.8'

services:
  react:
    build: ./front-end/front-end-kanban-app
    image: tung-react:0.0.1-SNAPSHOT
    container_name: front-end
    depends_on:
      - spring_boot
    ports:
      - '7000:3000'
    stdin_open: true
    tty: true
  spring_boot:
    build: ./back-end/back-end-kamban-app
    image: back-end-kamban-app:0.0.1-SNAPSHOT
    container_name: spring-boot
    depends_on:
      - mysql
    environment:
      SPRING_SERVER_PORT: 8001
      SPRING_DATABASE_PORT: 3306
      SPRING_DATABASE_NAME: ppmtcourse
      SPRING_DATABASE_ADDRESS: mysql
    ports:
      - '8000:8001'
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3000:3306'
    volumes:
      - mysql-1:/var/lib/mysql
      - ./mysql-docker/Books.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
    ports:
      - '3100:8080'

volumes:
  mysql-1:
    driver: local
