version: '3'
services:
  mysql-container:
    image: mysql:8.0.32
    networks:
      - project1-network
    volumes:
      - mysqlvol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ppmtcourse
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  #    ports:
  #      - 12345:3306
  spring_server1:
    networks:
      - project1-network
    depends_on:
      - mysql-container
    image: toolkithi/my-spring:latest
    restart: always
    environment:
      DB_USERNAME: root
      DB_HOST: mysql-container
      DB_PASSWORD: root
      DB_NAME: ppmtcourse
      PORT: 8080
      DB_PORT: 3306
      SERVER_NUMBER: 1
      JWT_SECRET: dpoasjkopwkqop32j1p3oj21pjpsaojdsapojopdjsdsadsa81203podjas0809s09
  spring_server2:
    networks:
      - project1-network
    depends_on:
      - mysql-container
    image: toolkithi/my-spring:latest
    restart: always
    environment:
      DB_USERNAME: root
      DB_HOST: mysql-container
      DB_PASSWORD: root
      DB_NAME: ppmtcourse
      PORT: 8081
      DB_PORT: 3306
      SERVER_NUMBER: 2
      JWT_SECRET: dpoasjkopwkqop32j1p3oj21pjpsaojdsapojopdjsdsadsa81203podjas0809s09
  proxy:
    networks:
      - project1-network
    image: toolkithi/mynginx:latest
    ports:
      - '80:80'
    restart: always
    depends_on:
      - spring_server1
networks:
  project1-network:
volumes:
  mysqlvol:
