spring:
  datasource:
    url: jdbc:mysql://192.168.1.183:3306/kanban
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
# server_number: ${SERVER_NUMBER}
